[database]
url = "sqlite:///machines.sqldb"
name = "fablab"

[MQTT]
broker = "192.168.1.123"
port = 1883
client_id = "backend"
topic = "machine/#"        # subscribe all topics beginning with machine
reply_subtopic = "/reply"  # appended to the main topic
